import React from 'react';
import ReactDOM from 'react-dom';
import App from './releasedList';
import * as serviceWorker from './serviceWorker';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'jquery/dist/jquery.min.js';
import 'bootstrap/dist/js/bootstrap.bundle.js';
import './styles.scss';
ReactDOM.render(<App />, document.getElementById('root'));
serviceWorker.unregister();